[package]
name = "use_scroll"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = "0.4"
console_error_panic_hook = "0.1"
console_log = "1"
log = "0.4"
leptos-use = { path = "../..", features = ["docs"] }
web-sys = "0.3"

[dev-dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3.0"
